import Head from "next/head"
import Image from "next/image"
import { useState } from "react"

import { Titillium_Web } from "next/font/google"
import { Back } from "@/components/Back"

import Background from "../../public/img/climate/background.svg"
import Weather from "../../public/img/climate/weather.svg"

const titillium = Titillium_Web({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
  variable: "--font-titillium",
})

export default function Climate() {
  return (
    <>
      <Head>
        <title>Climate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`${titillium.variable} font-sans bg-[#8E87FA] bg-[url('../../public/img/climate/background.svg')] bg-cover`}
      >
        <Back />

        <div className="h-screen flex items-center justify-center">
          <div>
            <div className="flex flex-row gap-8 flex-wrap">
              <div className="bg-[#6D67D0] w-[480px] h-[480px] rounded-xl relative px-4 py-3">
                <div className="flex justify-evenly">
                  <div className="bg-[#6660C8]/60 h-[60px] w-[146px] px-4 py-3 rounded-lg"></div>
                  <div className="bg-[#6660C8]/60 h-[60px] w-[146px] px-4 py-3 rounded-lg"></div>
                  <div className="bg-[#6660C8]/60 h-[60px] w-[146px] px-4 py-3 rounded-lg"></div>
                </div>
              </div>
              <Image
                src={Weather}
                alt="Weather"
                className="absolute z-10 left-80 top-44"
              />

              <div className="flex flex-col justify-between">
                <div className="flex justify-between">
                  <div className="bg-[#6D67D0] w-[277px] h-[244px] rounded-xl"></div>
                  <div className="bg-[#6D67D0] w-[277px] h-[244px] rounded-xl"></div>
                </div>

                <div className="bg-[#6D67D0] w-[578px] h-[212px] rounded-xl"></div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
