import Head from "next/head"
import Image from "next/image"
import { useState } from "react"

import { Lato } from "next/font/google"
import { Back } from "@/components/Back"

import Background from "../../public/img/climate/background.svg"
import Weather from "../../public/img/climate/weather.svg"
import Wind from "../../public/img/climate/vento.svg"
import Humidity from "../../public/img/climate/umidade.svg"
import Rain from "../../public/img/climate/chuva.svg"
import Locate from "../../public/img/climate/local.svg"
import Leaf from "../../public/img/climate/leaf.svg"

const lato = Lato({
  weight: ["400", "700", "900"],
  subsets: ["latin"],
  variable: "--font-lato",
})

interface AirQuality {
  num: number
  legend: string
}

const airQuality: Array<AirQuality> = [
  { num: 12.9, legend: "PM2.5" },
  { num: 12.9, legend: "PM10" },
  { num: 2.1, legend: "SO₂" },
  { num: 1.4, legend: "NO₂" },
  { num: 21.2, legend: "O₃" },
  { num: 0.7, legend: "CO" },
]

export default function Climate() {
  return (
    <>
      <Head>
        <title>Climate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`${lato.variable} font-lato bg-[#8E87FA] bg-[url('../../public/img/climate/background.svg')] bg-cover`}
      >
        <Back />

        <div className="h-screen">
          <div className="h-full w-full flex items-center justify-center">
            <div className="flex flex-row justify-center gap-8 flex-wrap px-4 py-4 ">
              <div className="bg-[#6D67D0] w-[30rem] h-[30rem] rounded-xl relative px-4 py-6 flex flex-col justify-between bg-[url('../../public/img/climate/bg-temp-now.jpeg')] bg-cover">
                <div className="flex items-center justify-end space-x-2">
                  <Image src={Locate} alt="Locate" />
                  <span className="font-bold text-[#C2BFF4]">
                    Rio do Sul, SC
                  </span>
                </div>

                <div className="flex flex-col justify-center items-center space-y-2">
                  <div>
                    <p className="font-bold text-7xl text-white flex items-start space-x-4">
                      18{" "}
                      <span className="font-light text-lg text-[#DAD8F7]">
                        °C
                      </span>
                    </p>
                  </div>
                  <div className="flex items-center space-x-2">
                    <span className="text-white text-xl">22°</span>
                    <span className="text-[#C2BFF4] text-xl">16°</span>
                  </div>
                </div>

                <div className="flex justify-center space-x-4 ">
                  <div className="bg-[#6660C8]/60 h-[60px] w-[140px] px-4 py-3 rounded-lg flex items-center justify-evenly">
                    <Image src={Wind} alt="Wind" />

                    <div className="flex flex-col justify-center items-start text-[#E7E6FB]">
                      <p className="text-sm">Vento</p>
                      <p className="text-sm">
                        <span className="text-[#E7E6FB] text-base">17</span>{" "}
                        Km/h
                      </p>
                    </div>
                  </div>

                  <div className="bg-[#6660C8]/60 h-[60px] w-[146px] px-4 py-3 rounded-lg flex items-center justify-evenly">
                    <Image src={Humidity} alt="Wind" />

                    <div className="flex flex-col justify-center items-start text-[#E7E6FB]">
                      <p className="text-sm">Umidade</p>
                      <p className="text-sm">
                        <span className="text-[#E7E6FB] text-base">31</span> %
                      </p>
                    </div>
                  </div>

                  <div className="bg-[#6660C8]/60 h-[60px] w-[146px] px-4 py-3 rounded-lg flex items-center justify-evenly">
                    <Image src={Rain} alt="Wind" />

                    <div className="flex flex-col justify-center items-start text-[#E7E6FB]">
                      <p className="text-sm">Chuva</p>
                      <p className="text-sm">
                        <span className="text-[#E7E6FB] text-base">10</span> %
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <Image
                src={Weather}
                alt="Weather"
                className="absolute z-10 left-80 top-44"
              />

              <div className="flex flex-col justify-between flex-wrap ">
                <div className="flex flex-row flex-wrap items-center justify-between ">
                  <div className="bg-[#6D67D0] w-[17.31rem] h-[15.25rem] rounded-xl py-4 px-4 flex flex-col justify-between">
                    <div className="flex items-center justify-center space-x-2">
                      <Image src={Leaf} alt="Leaf" className="" />
                      <span className="text-[#DAD8F7] font-bold">
                        Qualidade do ar
                      </span>
                    </div>

                    <div className="flex flex-col items-center justify-center space-y-1">
                      <span className="font-bold text-[#87EBCD] text-xl">
                        Boa
                      </span>
                      <span className="font-bold text-[#E7E6FB] text-5xl">
                        21
                      </span>
                    </div>

                    <div className="flex items-center justify-center space-x-3">
                      {airQuality.map((air, index) => {
                        return (
                          <div
                            key={index}
                            className="flex flex-col items-center justify-center"
                          >
                            <span className="text-[#87EBCD] text-sm">
                              {air.num}
                            </span>
                            <span className="text-[#E7E6FB] text-sm">
                              {air.legend}
                            </span>
                          </div>
                        )
                      })}
                    </div>
                  </div>
                  <div className="bg-[#6D67D0] w-[17.31rem] h-[15.25rem] rounded-xl"></div>
                </div>

                <div className="">
                  <div className="bg-[#6D67D0] w-[36.12rem] h-[13.25rem] rounded-xl"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
