import Head from "next/head"
import Image from "next/image"
import Link from "next/link"

import { IndexButton } from "../components/IndexButton"

import { Titillium_Web } from "next/font/google"

const titillium = Titillium_Web({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
  variable: "--font-titillium",
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Menu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${titillium.variable} font-titillium`}>
        <div className="w-screen h-screen flex justify-center items-center flex-col space-y-6">
          <div className="">
            <h1 className="text-3xl font-bold">Desafios</h1>
          </div>
          <div className="w-96 max-w-full flex items-center justify-center flex-col space-y-8 py-8 p-4">
            <IndexButton href="/loginpage" text="Login page" />
            <IndexButton href="/climate" text="Climate" />
            <IndexButton href="/kanban" text="Kanban" />
          </div>
        </div>
      </main>
    </>
  )
}
