import Head from "next/head"
import Image from "next/image"
import { ReactNode, useState } from "react"
import clsx from "clsx"

import {
  ClipboardIcon,
  UsersIcon,
  DocumentTextIcon,
  CogIcon,
} from "@heroicons/react/24/solid"

import { Inter } from "next/font/google"
import { Back } from "@/components/Back"

import Logo from "../../public/img/kanban/logo.svg"
import Pencil from "../../public/img/kanban/pencil.svg"

const inter = Inter({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-inter",
})

interface Menu {
  icon: ReactNode
  legend: any
}

const menu: Array<Menu> = [
  {
    icon: <ClipboardIcon className="h-8 w-8" />,
    legend: <span className="max-md:hidden">Boards</span>,
  },
  {
    icon: <UsersIcon className="h-8 w-8" />,
    legend: <span className="max-md:hidden">Equipes</span>,
  },
  {
    icon: <DocumentTextIcon className="h-8 w-8" />,
    legend: <span className="max-md:hidden">Relatórios</span>,
  },
  {
    icon: <CogIcon className="h-8 w-8" />,
    legend: <span className="max-md:hidden">Ajustes</span>,
  },
]

export default function Kanban() {
  return (
    <>
      <Head>
        <title>Kanban</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${inter.variable} font-inter bg-[#7C3AED]`}>
        <Back />

        <div id="app " className="grid grid-cols-[max-content_1fr] h-screen">
          <nav className="pt-12 pb-0 px-12 min-w-[11.5rem] max-md:min-w-[8rem]">
            <Image src={Logo} alt="Logo" />

            <ul className="mt-24 grid gap-14 ">
              {menu.map((item, index) => {
                return (
                  <li key={index}>
                    <a
                      href="#"
                      className={clsx(
                        "flex items-center gap-6 text-[#cab3ff] font-medium rounded hover:text-white [&.active]:text-white focus:outline-none focus:ring-2 focus:ring-[#9f67ff]",
                        {
                          active: index === 0,
                        }
                      )}
                    >
                      {item.icon}
                      {item.legend}
                    </a>
                  </li>
                )
              })}
            </ul>
          </nav>
          <div id="main" className="pt-3">
            <div
              id="inner"
              className="h-full bg-[#fbfaff] rounded-l-[32px] py-[3rem] px-[3.2rem]"
            >
              <section
                id="title-avatar"
                className="flex justify-between items-center flex-wrap-reverse py-[1.1rem] px-10"
              >
                <h1 className="flex items-center gap-5 text-4xl font-bold text-[#403937]">
                  Meu Kanban
                  <Image src={Pencil} alt="Pencil" />
                </h1>
                <Image
                  src={"https://github.com/alerrandrojanio.png"}
                  className="rounded-full"
                  width={80}
                  height={80}
                  alt="Avatar"
                />
              </section>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
